spring.application.name=emails
spring.datasource.url=jdbc:postgresql://localhost:5432/spamdetector
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD_SPAM:alunoguida22}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

training.batch-size=5000
training.insert-batch-size=1000
training.max-emails=0

spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration